name: ci
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'npm'
      - run: npm ci
      - run: npm test
  readmeTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: 'npm'
      - run: |
          npm pack
          mkdir tmp-ci
          perl -nle 'print $_ if /^<!-- BEGIN README TEST -->$/ .. /^<!-- END README TEST -->$/ and /^```typescript$/ .. /^```$/ and not /^```(?:typescript)?$/' ./README.md > tmp-ci/test-script.mts
          cp ./tsconfig-ci-readme-test.json tmp-ci/tsconfig.json
          cd tmp-ci
          npm i -S ../svelte-store-tree-0.1.1.tgz
          npm i -D typescript
          pwd
          ls node_modules
          npx tsc
          node test-script.mjs
